In [ ]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm
import yaml

In [ ]:
filenames = []
for file in os.listdir('data'):
    filenames.append(os.path.join('data',file))

In [ ]:
filenames[0:5]

['data/1422042.yaml',
 'data/1365323.yaml',
 'data/1376123.yaml',
 'data/1467704.yaml',
 'data/546462.yaml']

In [ ]:
final_df = pd.DataFrame()
counter = 0

In [ ]:
for file in tqdm(filenames):
    with open(file, 'r') as f:
        data = yaml.safe_load(f)

        # Ensure data is a dict or list (required for json_normalize)
        if isinstance(data, (dict, list)):
            df = pd.json_normalize(data)
            df['match_id'] = counter
            final_df = pd.concat([final_df, df], ignore_index=True)
            counter += 1
        else:
            print(f"Skipping {file}: Unexpected data type - {type(data)}")

  1%|          | 13/2080 [00:02<07:01,  4.90it/s]

Skipping data/README.txt: Unexpected data type - <class 'str'>

100%|██████████| 2080/2080 [33:57<00:00,  1.02it/s]

In [ ]:
backup = final_df.copy()

In [ ]:
final_df.info()
final_df.shape

<class 'pandas.core.frame.DataFrame'>
Index: 1368 entries, 0 to 2078
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   innings               1368 non-null   object
 1   info.dates            1368 non-null   object
 2   info.match_type       1368 non-null   object
 3   info.outcome.winner   1327 non-null   object
 4   info.overs            1368 non-null   int64
 5   info.player_of_match  1275 non-null   object
 6   info.teams            1368 non-null   object
 7   info.toss.decision    1368 non-null   object
 8   info.toss.winner      1368 non-null   object
 9   info.umpires          1339 non-null   object
 10  info.venue            1368 non-null   object
 11  match_id              1368 non-null   int64
 12  info.city             1277 non-null   object
dtypes: int64(2), object(11)
memory usage: 149.6+ KB

(1368, 13)

In [ ]:
final_df.head()

,innings,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Namibia', 'deliveri...",[2024-03-03],T20,NaN,20,NaN,"[Namibia, Netherlands]",field,Netherlands,"[DN Subedi, VK Jha]",Tribhuvan University International Cricket Gro...,0,Kirtipur
3,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2025-02-22],T20,NaN,20,NaN,"[Zimbabwe, Ireland]",field,Ireland,"[L Rusere, P Sizara]",Harare Sports Club,3,Harare
4,"[{'1st innings': {'team': 'Canada', 'deliverie...",[2012-03-22],T20,Ireland,20,[PR Stirling],"[Canada, Ireland]",bat,Canada,"[JD Cloete, CB Gaffaney]",Dubai International Cricket Stadium,4,NaN
5,"[{'1st innings': {'team': 'Suriname', 'deliver...",[2024-12-12],T20,Mexico,20,[PK Mohanarangam],"[Suriname, Mexico]",field,Mexico,"[H Grewal, M Abbott]","St George's College Ground, Buenos Aires",5,Buenos Aires
7,"[{'1st innings': {'team': 'Malawi', 'deliverie...",[2024-10-13],T20,Rwanda,20,[O Manishimwe],"[Malawi, Rwanda]",field,Rwanda,"[BP Jele, Osman Mhango]","TCA Oval, Blantyre",7,Blantyre

In [ ]:
required_columns = [
    'innings',
    'info.dates',
    'info.gender',
    'info.match_type',
    'info.outcome.winner',
    'info.overs',
    'info.player_of_match',
    'info.teams',
    'info.toss.decision',
    'info.toss.winner',
    'info.umpires',
    'info.venue',
    'match_id',
    'info.city'
]
existing_columns = [col for col in required_columns if col in final_df.columns]
final_df = final_df[existing_columns]

print("Filtered DataFrame shape:", final_df.shape)
final_df.head()

Filtered DataFrame shape: (1368, 13)

,innings,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Namibia', 'deliveri...",[2024-03-03],T20,NaN,20,NaN,"[Namibia, Netherlands]",field,Netherlands,"[DN Subedi, VK Jha]",Tribhuvan University International Cricket Gro...,0,Kirtipur
3,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2025-02-22],T20,NaN,20,NaN,"[Zimbabwe, Ireland]",field,Ireland,"[L Rusere, P Sizara]",Harare Sports Club,3,Harare
4,"[{'1st innings': {'team': 'Canada', 'deliverie...",[2012-03-22],T20,Ireland,20,[PR Stirling],"[Canada, Ireland]",bat,Canada,"[JD Cloete, CB Gaffaney]",Dubai International Cricket Stadium,4,NaN
5,"[{'1st innings': {'team': 'Suriname', 'deliver...",[2024-12-12],T20,Mexico,20,[PK Mohanarangam],"[Suriname, Mexico]",field,Mexico,"[H Grewal, M Abbott]","St George's College Ground, Buenos Aires",5,Buenos Aires
7,"[{'1st innings': {'team': 'Malawi', 'deliverie...",[2024-10-13],T20,Rwanda,20,[O Manishimwe],"[Malawi, Rwanda]",field,Rwanda,"[BP Jele, Osman Mhango]","TCA Oval, Blantyre",7,Blantyre

In [ ]:
final_df['info.match_type'].value_counts()

info.match_type
T20    1368
Name: count, dtype: int64

In [ ]:
final_df['info.overs'].value_counts()

info.overs
20    1364
50       4
Name: count, dtype: int64

In [ ]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs','info.match_type'],inplace=True)
final_df

<ipython-input-80-2ded84e4f63f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.overs','info.match_type'],inplace=True)

,innings,info.dates,info.outcome.winner,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Namibia', 'deliveri...",[2024-03-03],NaN,NaN,"[Namibia, Netherlands]",field,Netherlands,"[DN Subedi, VK Jha]",Tribhuvan University International Cricket Gro...,0,Kirtipur
3,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2025-02-22],NaN,NaN,"[Zimbabwe, Ireland]",field,Ireland,"[L Rusere, P Sizara]",Harare Sports Club,3,Harare
4,"[{'1st innings': {'team': 'Canada', 'deliverie...",[2012-03-22],Ireland,[PR Stirling],"[Canada, Ireland]",bat,Canada,"[JD Cloete, CB Gaffaney]",Dubai International Cricket Stadium,4,NaN
5,"[{'1st innings': {'team': 'Suriname', 'deliver...",[2024-12-12],Mexico,[PK Mohanarangam],"[Suriname, Mexico]",field,Mexico,"[H Grewal, M Abbott]","St George's College Ground, Buenos Aires",5,Buenos Aires
7,"[{'1st innings': {'team': 'Malawi', 'deliverie...",[2024-10-13],Rwanda,[O Manishimwe],"[Malawi, Rwanda]",field,Rwanda,"[BP Jele, Osman Mhango]","TCA Oval, Blantyre",7,Blantyre
...,...,...,...,...,...,...,...,...,...,...,...
2072,"[{'1st innings': {'team': 'Australia', 'delive...",[2010-05-07],Australia,[DA Warner],"[Australia, India]",field,India,"[BF Bowden, BR Doctrove]","Kensington Oval, Bridgetown",2072,Barbados
2073,"[{'1st innings': {'team': 'Nepal', 'deliveries...",[2023-11-05],NaN,[KH Prajapati],"[Nepal, Oman]",bat,Nepal,"[Gazi Sohel, Rashid Riaz]",Tribhuvan University International Cricket Gro...,2073,Kirtipur
2076,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",[2023-03-27],Bangladesh,[Rony Talukdar],"[Bangladesh, Ireland]",field,Ireland,"[Gazi Sohel, Masudur Rahman]","Zahur Ahmed Chowdhury Stadium, Chattogram",2076,Chattogram
2077,"[{'1st innings': {'team': 'England', 'deliveri...",[2013-06-27],NaN,NaN,"[England, New Zealand]",field,New Zealand,"[RK Illingworth, RT Robinson]",Kennington Oval,2077,London
2078,"[{'1st innings': {'team': 'France', 'deliverie...",[2023-07-14],Switzerland,[Faheem Nazir],"[France, Switzerland]",bat,France,"[D Kalloe, V Sridhar]",Marsa Sports Club,2078,Marsa

In [ ]:
import pickle
pickle.dump(final_df,open('dataset_level1.pkl','wb'))

In [ ]:
matches = pickle.load(open('dataset_level1.pkl','rb'))
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'MB Kruger',
   'batsman': 'JP Kotze'}},
 {0.2: {'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'MB Kruger',
   'batsman': 'JP Kotze'}},
 {0.3: {'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'MB Kruger',
   'batsman': 'JP Kotze'}},
 {0.4: {'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'MB Kruger',
   'batsman': 'JP Kotze'}},
 {0.5: {'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'non_striker': 'MB Kruger',
   'batsman': 'JP Kotze'}},
 {0.6: {'non_striker': 'MB Kruger',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'JP Kotze'}},
 {1.1: {'non_striker': 'JP Kotze',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {1.2: {'non_striker': 'JP Kotze',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {1.3: {'non_striker': 'JP Kotze',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'MB Kruger'}},
 {1.4: {'non_striker': 'JP Kotze',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MB Kruger'}},
 {1.5: {'non_striker': 'MB Kruger',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'JP Kotze'}},
 {1.6: {'non_striker': 'MB Kruger',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JP Kotze'}},
 {2.1: {'non_striker': 'JP Kotze',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {2.2: {'non_striker': 'JP Kotze',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {2.3: {'non_striker': 'JP Kotze',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {2.4: {'non_striker': 'JP Kotze',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {2.5: {'non_striker': 'JP Kotze',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'MB Kruger'}},
 {2.6: {'non_striker': 'JP Kotze',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MB Kruger'}},
 {3.1: {'non_striker': 'JP Kotze',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'MB Kruger'}},
 {3.2: {'non_striker': 'JP Kotze',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {3.3: {'non_striker': 'JP Kotze',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'MB Kruger'}},
 {3.4: {'non_striker': 'JP Kotze',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {3.5: {'non_striker': 'JP Kotze',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {3.6: {'non_striker': 'JP Kotze',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'MB Kruger'}},
 {4.1: {'non_striker': 'MB Kruger',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JP Kotze',
   'wicket': {'player_out': 'JP Kotze',
    'fielders': ['SA Edwards'],
    'kind': 'caught'}}},
 {4.2: {'non_striker': 'MB Kruger',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'JN Frylinck'}},
 {4.3: {'non_striker': 'MB Kruger',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Frylinck'}},
 {4.4: {'non_striker': 'MB Kruger',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Frylinck'}},
 {4.5: {'non_striker': 'MB Kruger',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Frylinck'}},
 {4.6: {'non_striker': 'JN Frylinck',
   'bowler': 'VJ Kingma',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger'}},
 {5.1: {'non_striker': 'MB Kruger',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Frylinck'}},
 {5.2: {'non_striker': 'MB Kruger',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Frylinck'}},
 {5.3: {'non_striker': 'MB Kruger',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Frylinck',
   'wicket': {'player_out': 'JN Frylinck', 'kind': 'caught and bowled'}}},
 {5.4: {'non_striker': 'MB Kruger',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Smit'}},
 {5.5: {'non_striker': 'MB Kruger',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Smit'}},
 {5.6: {'non_striker': 'MB Kruger',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Smit'}},
 {6.1: {'non_striker': 'JJ Smit',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MB Kruger',
   'wicket': {'player_out': 'MB Kruger', 'kind': 'bowled'}}},
 {6.2: {'non_striker': 'JJ Smit',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {6.3: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Smit'}},
 {6.4: {'non_striker': 'JJ Smit',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {6.5: {'non_striker': 'JJ Smit',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {6.6: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Smit'}},
 {7.1: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Smit'}},
 {7.2: {'non_striker': 'JJ Smit',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {7.3: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Smit'}},
 {7.4: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Smit'}},
 {7.5: {'non_striker': 'JJ Smit',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {7.6: {'non_striker': 'JJ Smit',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {8.1: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Smit'}},
 {8.2: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Smit'}},
 {8.3: {'non_striker': 'JJ Smit',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {8.4: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'JJ Smit'}},
 {8.5: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'JJ Smit'}},
 {8.6: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'RE van der Merwe',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Smit'}},
 {9.1: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Smit'}},
 {9.2: {'non_striker': 'JJ Smit',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {9.3: {'non_striker': 'JJ Smit',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {9.4: {'non_striker': 'JJ Smit',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {9.5: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Smit'}},
 {9.6: {'non_striker': 'JJ Smit',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {10.1: {'non_striker': 'JJ Smit',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {10.2: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Smit'}},
 {10.3: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Smit',
   'wicket': {'player_out': 'JJ Smit',
    'fielders': ['NRJ Croes'],
    'kind': 'caught'}}},
 {10.4: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'ZE Green'}},
 {10.5: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'ZE Green'}},
 {10.6: {'non_striker': 'ZE Green',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {11.1: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'ZE Green'}},
 {11.2: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'ZE Green'}},
 {11.3: {'non_striker': 'ZE Green',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {11.4: {'non_striker': 'ZE Green',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'JN Loftie-Eaton'}},
 {11.5: {'non_striker': 'ZE Green',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'JN Loftie-Eaton'}},
 {11.6: {'non_striker': 'ZE Green',
   'bowler': 'M Levitt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {12.1: {'non_striker': 'ZE Green',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {12.2: {'non_striker': 'ZE Green',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {12.3: {'non_striker': 'ZE Green',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {12.4: {'non_striker': 'ZE Green',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {12.5: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'ZE Green'}},
 {12.6: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'A Dutt',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'ZE Green'}},
 {13.1: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'SA Engelbrecht',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'ZE Green'}},
 {13.2: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'SA Engelbrecht',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'ZE Green'}},
 {13.3: {'non_striker': 'ZE Green',
   'bowler': 'SA Engelbrecht',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'JN Loftie-Eaton'}},
 {13.4: {'non_striker': 'ZE Green',
   'bowler': 'SA Engelbrecht',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'JN Loftie-Eaton'}},
 {13.5: {'non_striker': 'ZE Green',
   'bowler': 'SA Engelbrecht',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {13.6: {'non_striker': 'ZE Green',
   'bowler': 'SA Engelbrecht',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {14.1: {'non_striker': 'ZE Green',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JN Loftie-Eaton'}},
 {14.2: {'non_striker': 'ZE Green',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {14.3: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'ZE Green'}},
 {14.4: {'non_striker': 'ZE Green',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'JN Loftie-Eaton'}},
 {14.5: {'non_striker': 'ZE Green',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JN Loftie-Eaton'}},
 {14.6: {'non_striker': 'JN Loftie-Eaton',
   'bowler': 'T van der Gugten',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'ZE Green'}}]

In [ ]:
count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count+=1
        continue
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    delivery_df =  pd.concat([delivery_df, loop_df], ignore_index=True)

In [ ]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Namibia, Netherlands]",Namibia,0.1,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
1,2,"[Namibia, Netherlands]",Namibia,0.2,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
2,2,"[Namibia, Netherlands]",Namibia,0.3,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
3,2,"[Namibia, Netherlands]",Namibia,0.4,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
4,2,"[Namibia, Netherlands]",Namibia,0.5,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...
...,...,...,...,...,...,...,...,...,...,...
163216,1365,"[France, Switzerland]",France,19.2,Noman Amjad,K Fletcher,2,0,Marsa,Marsa Sports Club
163217,1365,"[France, Switzerland]",France,19.3,Noman Amjad,K Fletcher,0,0,Marsa,Marsa Sports Club
163218,1365,"[France, Switzerland]",France,19.4,Noman Amjad,K Fletcher,1,0,Marsa,Marsa Sports Club
163219,1365,"[France, Switzerland]",France,19.5,Usman Khan,K Fletcher,0,0,Marsa,Marsa Sports Club
163220,1365,"[France, Switzerland]",France,19.6,Usman Khan,K Fletcher,1,0,Marsa,Marsa Sports Club

In [ ]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [ ]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [ ]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Namibia, Netherlands]",Namibia,0.1,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
1,2,"[Namibia, Netherlands]",Namibia,0.2,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
2,2,"[Namibia, Netherlands]",Namibia,0.3,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
3,2,"[Namibia, Netherlands]",Namibia,0.4,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
4,2,"[Namibia, Netherlands]",Namibia,0.5,JP Kotze,VJ Kingma,0,0,Kirtipur,Tribhuvan University International Cricket Gro...,Netherlands
...,...,...,...,...,...,...,...,...,...,...,...
163216,1365,"[France, Switzerland]",France,19.2,Noman Amjad,K Fletcher,2,0,Marsa,Marsa Sports Club,Switzerland
163217,1365,"[France, Switzerland]",France,19.3,Noman Amjad,K Fletcher,0,0,Marsa,Marsa Sports Club,Switzerland
163218,1365,"[France, Switzerland]",France,19.4,Noman Amjad,K Fletcher,1,0,Marsa,Marsa Sports Club,Switzerland
163219,1365,"[France, Switzerland]",France,19.5,Usman Khan,K Fletcher,0,0,Marsa,Marsa Sports Club,Switzerland
163220,1365,"[France, Switzerland]",France,19.6,Usman Khan,K Fletcher,1,0,Marsa,Marsa Sports Club,Switzerland

In [ ]:
delivery_df.drop(columns=['teams'],inplace=True)

In [ ]:
delivery_df['batting_team'].unique()

array(['Namibia', 'Zimbabwe', 'Canada', 'Suriname', 'Malawi', 'Sri Lanka',
       'Australia', 'Botswana', 'Bangladesh', 'Malaysia', 'Israel',
       'Uganda', 'Singapore', 'India', 'Austria', 'Sierra Leone',
       'New Zealand', 'Indonesia', 'United States of America',
       'Netherlands', 'Finland', 'West Indies', 'Pakistan', 'England',
       'South Africa', 'Hong Kong', 'Bhutan', 'Papua New Guinea', 'Nepal',
       'Oman', 'Jersey', 'Japan', 'Denmark', 'Vanuatu', 'Maldives',
       'Cameroon', 'Tanzania', 'Cayman Islands', 'United Arab Emirates',
       'Spain', 'Mongolia', 'Argentina', 'Bahamas', 'Gibraltar',
       'Nigeria', 'Czech Republic', 'Mexico', 'Panama', 'Saudi Arabia',
       'Bahrain', 'Switzerland', 'Portugal', 'Scotland', 'Greece',
       'Norway', 'Mali', 'Guernsey', 'Myanmar', 'Ireland', 'Luxembourg',
       'Ivory Coast', 'Kuwait', 'Bermuda', 'Rwanda', 'Malta', 'France',
       'Seychelles', 'Cyprus', 'Estonia', 'Ghana', 'Brazil', 'Gambia',
       'Serbia', 'Croatia', 'Kenya', 'Italy', 'Germany', 'Belize',
       'Hungary', 'Philippines', 'Qatar', 'Isle of Man', 'Belgium',
       'Chile', 'Lesotho', 'Thailand', 'Mozambique', 'Eswatini',
       'Romania', 'Cambodia', 'Bulgaria', 'Samoa', 'Slovenia',
       'St Helena', 'Sweden', 'Turkey', 'Fiji', 'South Korea',
       'Costa Rica', 'China'], dtype=object)

In [ ]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'
]

In [ ]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [ ]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
508,7,Sri Lanka,0.1,DPMD Jayawardene,NL McCullum,1,0,Guyana,Providence Stadium,New Zealand
509,7,Sri Lanka,0.2,TM Dilshan,NL McCullum,1,0,Guyana,Providence Stadium,New Zealand
510,7,Sri Lanka,0.3,TM Dilshan,NL McCullum,0,0,Guyana,Providence Stadium,New Zealand
511,7,Sri Lanka,0.4,TM Dilshan,NL McCullum,0,0,Guyana,Providence Stadium,New Zealand
512,7,Sri Lanka,0.5,TM Dilshan,NL McCullum,0,0,Guyana,Providence Stadium,New Zealand
...,...,...,...,...,...,...,...,...,...,...
162840,1361,Australia,19.4,MEK Hussey,A Nehra,0,0,Barbados,"Kensington Oval, Bridgetown",India
162841,1361,Australia,19.5,MEK Hussey,A Nehra,0,MEK Hussey,Barbados,"Kensington Oval, Bridgetown",India
162842,1361,Australia,19.6,SPD Smith,A Nehra,1,0,Barbados,"Kensington Oval, Bridgetown",India
163090,1364,England,0.1,MJ Lumb,MJ McClenaghan,2,0,London,Kennington Oval,New Zealand
163091,1364,England,0.2,MJ Lumb,MJ McClenaghan,0,MJ Lumb,London,Kennington Oval,New Zealand

In [ ]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [ ]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
508,7,Sri Lanka,New Zealand,0.1,1,0,Guyana,Providence Stadium
509,7,Sri Lanka,New Zealand,0.2,1,0,Guyana,Providence Stadium
510,7,Sri Lanka,New Zealand,0.3,0,0,Guyana,Providence Stadium
511,7,Sri Lanka,New Zealand,0.4,0,0,Guyana,Providence Stadium
512,7,Sri Lanka,New Zealand,0.5,0,0,Guyana,Providence Stadium
...,...,...,...,...,...,...,...,...
162840,1361,Australia,India,19.4,0,0,Barbados,"Kensington Oval, Bridgetown"
162841,1361,Australia,India,19.5,0,MEK Hussey,Barbados,"Kensington Oval, Bridgetown"
162842,1361,Australia,India,19.6,1,0,Barbados,"Kensington Oval, Bridgetown"
163090,1364,England,New Zealand,0.1,2,0,London,Kennington Oval
163091,1364,England,New Zealand,0.2,0,MJ Lumb,London,Kennington Oval

In [ ]:
pickle.dump(output,open('dataset_level2.pkl','wb'))

In [ ]:
output[output['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        2349
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                    955
Adelaide Oval                               373
Sydney Cricket Ground                       373
Sharjah Cricket Stadium                     127
Name: count, dtype: int64

In [ ]:
x = np.where(output['city'].isnull(), output['venue'].str.split().apply(lambda x:x[0]), output['city'])

In [ ]:
output['city'] = x

<ipython-input-99-d2c7fa334a48>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  output['city'] = x

In [ ]:
output.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [ ]:
output.drop(columns=['venue'],inplace=True)

<ipython-input-101-0416bd494a13>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  output.drop(columns=['venue'],inplace=True)

In [ ]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
508,7,Sri Lanka,New Zealand,0.1,1,0,Guyana
509,7,Sri Lanka,New Zealand,0.2,1,0,Guyana
510,7,Sri Lanka,New Zealand,0.3,0,0,Guyana
511,7,Sri Lanka,New Zealand,0.4,0,0,Guyana
512,7,Sri Lanka,New Zealand,0.5,0,0,Guyana
...,...,...,...,...,...,...,...
162840,1361,Australia,India,19.4,0,0,Barbados
162841,1361,Australia,India,19.5,0,MEK Hussey,Barbados
162842,1361,Australia,India,19.6,1,0,Barbados
163090,1364,England,New Zealand,0.1,2,0,London
163091,1364,England,New Zealand,0.2,0,MJ Lumb,London

In [ ]:
total_df = output.groupby('match_id').sum()['runs'].reset_index()
output = output.merge(total_df,on='match_id')

In [ ]:
output

,match_id,batting_team,bowling_team,ball,runs_x,player_dismissed,city,runs_y
0,7,Sri Lanka,New Zealand,0.1,1,0,Guyana,135
1,7,Sri Lanka,New Zealand,0.2,1,0,Guyana,135
2,7,Sri Lanka,New Zealand,0.3,0,0,Guyana,135
3,7,Sri Lanka,New Zealand,0.4,0,0,Guyana,135
4,7,Sri Lanka,New Zealand,0.5,0,0,Guyana,135
...,...,...,...,...,...,...,...,...
51344,1361,Australia,India,19.4,0,0,Barbados,184
51345,1361,Australia,India,19.5,0,MEK Hussey,Barbados,184
51346,1361,Australia,India,19.6,1,0,Barbados,184
51347,1364,England,New Zealand,0.1,2,0,London,2
51348,1364,England,New Zealand,0.2,0,MJ Lumb,London,2

In [ ]:
output.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51349 entries, 0 to 51348
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          51349 non-null  int64
 1   batting_team      51349 non-null  object
 2   bowling_team      51349 non-null  object
 3   ball              51349 non-null  float64
 4   runs_x            51349 non-null  int64
 5   player_dismissed  51349 non-null  object
 6   city              51349 non-null  object
 7   runs_y            51349 non-null  int64
dtypes: float64(1), int64(3), object(4)
memory usage: 3.1+ MB

In [ ]:
output['runs_x'] = pd.to_numeric(output['runs_x'], errors='coerce')

In [ ]:
output['current_score'] = output.groupby('match_id')['runs_x'].cumsum()

In [ ]:
output['over'] = output['ball'].apply(lambda x:str(x).split(".")[0])
output['ball_no'] = output['ball'].apply(lambda x:str(x).split(".")[1])

In [ ]:
output['balls_bowled'] = (output['over'].astype('int')*6) + output['ball_no'].astype('int')

In [ ]:
output['crr'] = round((output['current_score']*6)/output['balls_bowled'],2)

In [ ]:
output['player_dismissed'] = output['player_dismissed'].apply(lambda x: 0 if x == '0' else 1)
output['player_dismissed'] = output['player_dismissed'].astype(int)
output['player_dismissed'] = output.groupby('match_id')['player_dismissed'].cumsum()
output['wickets_left'] = 10 - output['player_dismissed']

In [ ]:
final_df = output[['match_id','batting_team','bowling_team','runs_x','current_score','balls_bowled','wickets_left','crr','city','runs_y']]

In [ ]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,balls_bowled,wickets_left,crr,city,runs_y
0,7,Sri Lanka,New Zealand,1,1,1,9,6.00,Guyana,135
1,7,Sri Lanka,New Zealand,1,2,2,8,6.00,Guyana,135
2,7,Sri Lanka,New Zealand,0,2,3,7,4.00,Guyana,135
3,7,Sri Lanka,New Zealand,0,2,4,6,3.00,Guyana,135
4,7,Sri Lanka,New Zealand,0,2,5,5,2.40,Guyana,135
...,...,...,...,...,...,...,...,...,...,...
51344,1361,Australia,India,0,183,118,-109,9.31,Barbados,184
51345,1361,Australia,India,0,183,119,-110,9.23,Barbados,184
51346,1361,Australia,India,1,184,120,-111,9.20,Barbados,184
51347,1364,England,New Zealand,2,2,1,9,12.00,London,2
51348,1364,England,New Zealand,0,2,2,8,6.00,London,2

In [ ]:
final_df = final_df.sample(final_df.shape[0])

In [ ]:
final_df['balls_left'] = 120 - final_df['balls_bowled']
final_df['balls_left'] = final_df['balls_left'].apply(lambda x:0 if x<0 else x)

In [ ]:
final_df['crr'] = round((final_df['current_score']*6)/final_df['balls_bowled'],2)

In [ ]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,balls_bowled,wickets_left,crr,city,runs_y,balls_left
7216,167,South Africa,Sri Lanka,1,84,99,-90,5.09,Colombo,115,21
7194,167,South Africa,Sri Lanka,0,58,77,-68,4.52,Colombo,115,43
43531,1140,New Zealand,Sri Lanka,1,100,72,-68,8.33,Mount Maunganui,186,48
9519,232,Sri Lanka,Bangladesh,0,68,57,-48,7.16,Sylhet,174,63
20740,503,South Africa,Australia,4,7,11,-1,3.82,Colombo,146,109
...,...,...,...,...,...,...,...,...,...,...,...
49354,1311,Australia,Pakistan,2,167,102,-93,9.82,St Lucia,191,18
8381,194,New Zealand,India,2,44,49,-39,5.39,Nagpur,126,71
9618,234,Pakistan,New Zealand,4,47,33,-24,8.55,Pallekele,177,87
24205,597,England,South Africa,1,115,116,-106,5.95,Chester-le-Street,118,4
42599,1114,New Zealand,West Indies,0,1,4,6,1.50,Hamilton,191,116

In [ ]:
final_df.isnull().sum()
final_df.dropna(inplace=True)

In [ ]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,balls_bowled,wickets_left,crr,city,runs_y,balls_left
7216,167,South Africa,Sri Lanka,1,84,99,-90,5.09,Colombo,115,21
7194,167,South Africa,Sri Lanka,0,58,77,-68,4.52,Colombo,115,43
43531,1140,New Zealand,Sri Lanka,1,100,72,-68,8.33,Mount Maunganui,186,48
9519,232,Sri Lanka,Bangladesh,0,68,57,-48,7.16,Sylhet,174,63
20740,503,South Africa,Australia,4,7,11,-1,3.82,Colombo,146,109
...,...,...,...,...,...,...,...,...,...,...,...
49354,1311,Australia,Pakistan,2,167,102,-93,9.82,St Lucia,191,18
8381,194,New Zealand,India,2,44,49,-39,5.39,Nagpur,126,71
9618,234,Pakistan,New Zealand,4,47,33,-24,8.55,Pallekele,177,87
24205,597,England,South Africa,1,115,116,-106,5.95,Chester-le-Street,118,4
42599,1114,New Zealand,West Indies,0,1,4,6,1.50,Hamilton,191,116

In [ ]:
eligible_cities = final_df['city'].value_counts()[final_df['city'].value_counts() > 600].index.tolist()
final_df = final_df[final_df['city'].isin(eligible_cities)]

In [ ]:
X = final_df.drop(columns=['match_id','runs_x','runs_y'])
y = final_df['runs_y']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
X_test

,batting_team,bowling_team,current_score,balls_bowled,wickets_left,crr,city,balls_left
14793,New Zealand,England,11,9,1,7.33,Hamilton,111
27035,Sri Lanka,Australia,11,15,-8,4.40,Melbourne,105
30414,West Indies,New Zealand,67,74,-66,5.43,Auckland,46
5451,West Indies,Australia,87,51,-44,10.24,Barbados,69
3390,Sri Lanka,New Zealand,24,16,-8,9.00,Auckland,104
...,...,...,...,...,...,...,...,...
21810,Australia,India,88,67,-58,7.88,Mumbai,53
10104,Australia,India,38,23,-13,9.91,Sydney,97
21060,Bangladesh,India,34,36,-27,5.67,Mirpur,84
24913,South Africa,West Indies,0,2,8,0.00,Durban,118
14637,Sri Lanka,West Indies,140,96,-90,8.75,Dambulla,24

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error

trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough')

In [ ]:
pipe = Pipeline([
    ('preprocess', trf),
    ('model', RandomForestRegressor())
])

In [ ]:
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

R2 Score: 0.9258522786669309
MAE: 3.6568719950622293